# Generated by Django 5.0.4 on 2024-04-17 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_rename_dadosmedico_doctordata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordata',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='cedula_identidade_medica',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='valor_consulta',
        ),
        migrations.RemoveField(
            model_name='specialties',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='specialties',
            name='icone',
        ),
        migrations.AddField(
            model_name='doctordata',
            name='consultation_fee',
            field=models.FloatField(
                default=100, verbose_name='Consultation Fee'
            ),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='description',
            field=models.TextField(
                blank=True, null=True, verbose_name='Description'
            ),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='medical_identification',
            field=models.ImageField(
                default=1234,
                upload_to='medical_identifications',
                verbose_name='Medical Identification',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctordata',
            name='name',
            field=models.CharField(
                default=1, max_length=100, verbose_name='Name'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctordata',
            name='neighborhood',
            field=models.CharField(
                default=1, max_length=100, verbose_name='Neighborhood'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctordata',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctordata',
            name='photo',
            field=models.ImageField(
                default=1, upload_to='profile_photos', verbose_name='Photo'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctordata',
            name='specialty',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='doctor.specialties',
                verbose_name='Specialty',
            ),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='street',
            field=models.CharField(
                default=1, max_length=100, verbose_name='Street'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctordata',
            name='zip_code',
            field=models.CharField(
                default=1, max_length=15, verbose_name='Zip Code'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialties',
            name='icon',
            field=models.ImageField(
                blank=True, null=True, upload_to='icons', verbose_name='Icon'
            ),
        ),
        migrations.AddField(
            model_name='specialties',
            name='specialty',
            field=models.CharField(
                default=1, max_length=100, verbose_name='Specialty'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='crm',
            field=models.CharField(max_length=30, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='rg',
            field=models.ImageField(upload_to='rgs', verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
    ]
