# Generated by Django 5.0.4 on 2024-04-17 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_doctordata_medical_identification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordata',
            name='zip_code',
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        code='invalid_cep',
                        message='Enter a valid ZIP code in the format XXXXX-XXX.',
                        regex='^\\d{5}-\\d{3}$',
                    )
                ],
                verbose_name='Zip Code',
            ),
        ),
    ]
