# Generated by Django 5.0.4 on 2024-04-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='documents',
            new_name='document',
        ),
    ]
