# Generated by Django 5.0.4 on 2024-04-17 00:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DadosMedico',
            new_name='DoctorData',
        ),
        migrations.RenameModel(
            old_name='Especialidades',
            new_name='Specialties',
        ),
    ]
