# Generated by Django 5.0.4 on 2024-04-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_doctordata_bairro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordata',
            name='medical_identification',
        ),
        migrations.AddField(
            model_name='doctordata',
            name='digital_crm',
            field=models.ImageField(
                default=1,
                upload_to='medical_identifications',
                verbose_name='Digital CRM',
            ),
            preserve_default=False,
        ),
    ]
