# Generated by Django 5.0.4 on 2024-04-17 17:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'doctor',
            '0006_alter_doctordata_options_alter_specialties_options_and_more',
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenDates',
            new_name='OpenedDates',
        ),
        migrations.AlterModelOptions(
            name='openeddates',
            options={
                'verbose_name': 'opened date',
                'verbose_name_plural': 'opened dates',
            },
        ),
    ]
