# Generated by Django 5.0.4 on 2024-04-18 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0008_rename_openeddates_openeddate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('A', 'Scheduled'),
                            ('F', 'Finished'),
                            ('C', 'Cancelled'),
                            ('I', 'Started'),
                        ],
                        default='A',
                        max_length=1,
                        verbose_name='status',
                    ),
                ),
                (
                    'link',
                    models.URLField(
                        blank=True, null=True, verbose_name='link'
                    ),
                ),
                (
                    'opened_date',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='doctor.openeddate',
                        verbose_name='opened_date',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='patient',
                    ),
                ),
            ],
        ),
    ]
